site_name: Fusus
site_description: >- 
  Pipeline from scanned pages of Arabic Medieval books to readable text.
  With cleaning before OCR, OCR itself, and postprocessing.

site_url: 'https://among.github.io/fusus/'
site_author: Cornelis van Lit, Dirk Roorda

repo_name: among/fusus
repo_url: 'https://github.com/among/fusus/'

theme:
  name: dans
  logo: 'images/fusus-small.png'
  favicon: 'images/icon/favicon.ico'
  development: true
  development_label: 'work in progress'
  feature:
    tabs: true

strict: false

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: Dans-labs
      repo: mkdocs-dans
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - markdownextradata
  - search
  - minify:
      minify_html: true

nav:
  - Home: 'index.md'
  - Operation:
    - install: 'install.md'
    - use: 'use.md'
    - methods: 'methods.md'
    - docstrings: 'apidocs/html/pipeline/index.html'

extra:
  among: https://github.com/among
  dans: https://dans.knaw.nl/en
  fusus: https://github.com/among/fusus/blob/master
  fususloc: https://github.com/among/fusus
  jup: https://jupyter.org
  mkdocs: https://mkdocs.readthedocs.io/en/stable/
  python: https://docs.python.org/3
  pythond: https://www.python.org/downloads/
  wikip: https://en.wikipedia.org/wiki
  zenodo: https://zenodo.org
